# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address Line 2'),
        ),
    ]
