# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-18 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('main_phone', models.CharField(max_length=10)),
                ('alt_phone', models.CharField(max_length=10, null=True)),
                ('relationship', models.CharField(choices=[('Sib', 'Sibling'), ('M', 'Mother'), ('F', 'Father'), ('C', 'Cousin')], max_length=10)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Outpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('idd', models.PositiveIntegerField(default=237)),
                ('main_phone', models.CharField(max_length=10)),
                ('alt_phone', models.CharField(max_length=10, null=True)),
                ('occupation', models.CharField(max_length=30, null=True)),
                ('pregnant', models.NullBooleanField()),
                ('signed_consent_for_roi', models.BooleanField(default=True)),
                ('reason_for_not_signing_consent', models.TextField(null=True)),
                ('admitted', models.NullBooleanField()),
                ('consultation_fee', models.IntegerField()),
                ('has_all_prescribed_medications', models.BooleanField()),
                ('issues_with_taking_medicatin', models.BooleanField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address')),
            ],
        ),
    ]
