# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('outpatients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'diagnoses',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'diagnosis_categories',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('main_phone', models.CharField(max_length=10)),
                ('alt_phone', models.CharField(max_length=10, null=True)),
                ('relationship', models.CharField(choices=[('Sib', 'Sibling'), ('M', 'Mother'), ('F', 'Father'), ('C', 'Cousin')], max_length=10)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address')),
            ],
            options={
                'db_table': 'emergency_contacts',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'medications',
            },
        ),
        migrations.CreateModel(
            name='MedicationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_num', models.IntegerField()),
                ('route', models.CharField(max_length=10)),
                ('frequency', models.CharField(max_length=10)),
                ('dosage_unit', models.CharField(max_length=10)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='outpatients.Medication')),
            ],
            options={
                'db_table': 'prescribedmeds',
            },
        ),
        migrations.RemoveField(
            model_name='emergency_contact',
            name='address',
        ),
        migrations.AlterModelTable(
            name='outpatient',
            table='outpatients',
        ),
        migrations.DeleteModel(
            name='Emergency_Contact',
        ),
        migrations.AddField(
            model_name='prescribedmed',
            name='outpatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='outpatients.Outpatient'),
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.MedicationCategory'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='outpatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Outpatient'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.DiagnosisCategories'),
        ),
        migrations.AddField(
            model_name='outpatient',
            name='diagnoses',
            field=models.ManyToManyField(to='outpatients.Diagnosis'),
        ),
    ]
