# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('outpatients', '0003_auto_20170719_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_date', models.DateTimeField()),
                ('followed_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'certifications',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('main_phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address')),
                ('certifications', models.ManyToManyField(to='outpatients.Certification')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address')),
                ('departments', models.ManyToManyField(to='outpatients.Department')),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'specialties',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('doctors_note', models.TextField()),
                ('patient_received_ed', models.BooleanField()),
                ('lab_fee', models.FloatField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Doctor')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Facility')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='prescribers',
            field=models.ManyToManyField(through='outpatients.PrescribedMed', to='outpatients.Outpatient'),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='consultation_fee',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='visit',
            name='outpatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Outpatient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(to='outpatients.Specialty'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Department'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Facility'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='outpatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Outpatient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Visit'),
        ),
        migrations.AddField(
            model_name='outpatient',
            name='allegies',
            field=models.ManyToManyField(to='outpatients.Allergy'),
        ),
    ]
