# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('outpatients', '0004_auto_20170719_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_patient', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('appt_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.Appointment')),
            ],
            options={
                'db_table': 'appt_reminders',
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_patient', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'med_reminders',
            },
        ),
        migrations.CreateModel(
            name='PatientCareCoordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('main_phone', models.CharField(max_length=10)),
                ('alt_phone', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address')),
            ],
            options={
                'db_table': 'pccs',
            },
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='pcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.PatientCareCoordinator'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='prescribed_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.PrescribedMed'),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='pcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatients.PatientCareCoordinator'),
        ),
    ]
