# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0007_auto_20170719_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='appointmentreminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointmentreminder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='medicationreminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicationreminder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='outpatient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='outpatient',
            name='updated_at',
        ),
    ]
