# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outpatients', '0008_auto_20170719_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcarecoordinator',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medicationreminder',
            name='pcc',
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='pcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PatientCareCoordinator',
        ),
    ]
