# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0010_auto_20170722_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outpatient',
            old_name='allegies',
            new_name='allergies',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='prescribers',
        ),
        migrations.AddField(
            model_name='outpatient',
            name='medications',
            field=models.ManyToManyField(through='outpatients.PrescribedMed', to='outpatients.Medication'),
        ),
    ]
