# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0011_auto_20170722_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmed',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
