# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0012_prescribedmed_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpatient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='outpatient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outpatient',
            name='surname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
