# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0013_auto_20170725_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatient',
            name='alt_phone',
            field=models.CharField(blank=True, default='N/A', max_length=10),
        ),
    ]
