# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0014_auto_20170725_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatient',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Address'),
        ),
    ]
