# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0015_auto_20170725_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatient',
            name='consultation_fee',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='reason_for_not_signing_consent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
