# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outpatients', '0016_auto_20170726_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outpatient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outpatient',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outpatient',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Address'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Sib', 'Sibling'), ('M', 'Mother'), ('F', 'Father'), ('C', 'Cousin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Address'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='departments',
            field=models.ManyToManyField(blank=True, to='outpatients.Department'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='outpatients.Allergy'),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, to='outpatients.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctors_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lab_fee',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_received_ed',
            field=models.BooleanField(default=False),
        ),
    ]
